<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <meta charset="windows-1252">
        <title>Materiales de Laboratorio</title>
        <link rel="stylesheet" href="Estilos/PageU.css"/>
        <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"> <!-- para poner el shoopping cart symbol-->
    </head>
    <body>
        <div id="container">
          <div id="banner">
              <div style="display: inline-block; width: 737px; text-align: center">
                  <br>
                <p> Materiales de Laboratorio para estudiantes de Ingenieria Electronica<p/> 
              </div>
              <!--BOTON DE SHOPPING CART-->
              <div style="display: inline-block; float: right ; clear:right;" >
                  <a href="aqui" class="btn btn-info btn-lg">
                <span class="glyphicon glyphicon-shopping-cart" > Cart: 0</span> 
                </a>
              </div>
                  <!-- 
                  <button type="button" class="btn btn-default btn-sm">
                      <span class="glyphicon glyphicon-shopping-cart"></span> Shopping Cart
                  </button>
                  </p>-->
           </div>
           <div id="nav">
              <span id="urhere"><a href="index.php">HOME</a></span>
              <span><a href="MostrarTabla.php">MOSTRAR LA TABLA</a></span>
              <span><a href="Login.php">LOGIN</a></span>
           </div> <!-- end div "nav" -->

          <div id="content">
            <p>You should already have some content from previous sessions – copy and paste that into this section.</p>
            
            <body>
		
		<!-- Start cssSlider.com -->
		<!-- Generated by cssSlider.com 2.1 -->
                <link rel="stylesheet" href="Estilos/cssslider_files/csss_engine1/style.css">
		<!--[if IE]><link rel="stylesheet" href="cssslider_files/csss_engine1/ie.css"><![endif]-->
		<!--[if lte IE 9]><script type="text/javascript" src="cssslider_files/csss_engine1/ie.js"></script><![endif]-->
		 <div class="csslider1 autoplay ">
		<input name="cs_anchor1" id="cs_slide1_0" class="cs_anchor slide" type="radio">
		<input name="cs_anchor1" id="cs_slide1_1" class="cs_anchor slide" type="radio">
		<input name="cs_anchor1" id="cs_slide1_2" class="cs_anchor slide" type="radio">
		<input name="cs_anchor1" id="cs_slide1_3" class="cs_anchor slide" type="radio">
		<input name="cs_anchor1" id="cs_slide1_4" class="cs_anchor slide" type="radio">
		<input name="cs_anchor1" id="cs_play1" class="cs_anchor" checked="" type="radio">
		<input name="cs_anchor1" id="cs_pause1_0" class="cs_anchor pause" type="radio">
		<input name="cs_anchor1" id="cs_pause1_1" class="cs_anchor pause" type="radio">
		<input name="cs_anchor1" id="cs_pause1_2" class="cs_anchor pause" type="radio">
		<input name="cs_anchor1" id="cs_pause1_3" class="cs_anchor pause" type="radio">
		<input name="cs_anchor1" id="cs_pause1_4" class="cs_anchor pause" type="radio">
		<ul>
                    <li class="cs_skeleton"><img src="Estilos/cssslider_files/csss_images1/brazo.jpg" style="width: 100%;"></li>
                    <li class="num0 img slide"> <img src="Estilos/cssslider_files/csss_images1/brazo.jpg" alt="Brazo Robotico" title="Brazo Robotico"></li>
                    <li class="num1 img slide"> <img src="Estilos/cssslider_files/csss_images1/rasp.jpg" alt="raspberry pi 2" title="raspberry pi 2"></li>
                    <li class="num2 img slide"> <img src="Estilos/cssslider_files/csss_images1/daq.jpg" alt="DAQ" title="DAQ"></li>
                    <li class="num3 img slide"> <img src="Estilos/cssslider_files/csss_images1/fuente.jpg" alt="Fuente" title="Fuente"></li>
                    <li class="num4 img slide"> <img src="Estilos/cssslider_files/csss_images1/generador_de_funciones.jpg" alt="Generador de Funciones" title="Generador de Funciones"></li>
		</ul><div class="cs_engine"><a href="http://cssslider.com">bootstrap slider</a> by cssSlider.com v2.1</div>
		<div class="cs_description">
			<label class="num0"><span class="cs_title"><span class="cs_wrapper">Brazo Robotico</span></span></label>
			<label class="num1"><span class="cs_title"><span class="cs_wrapper">raspberry pi 2</span></span></label>
			<label class="num2"><span class="cs_title"><span class="cs_wrapper">DAQ</span></span></label>
			<label class="num3"><span class="cs_title"><span class="cs_wrapper">Fuente</span></span></label>
			<label class="num4"><span class="cs_title"><span class="cs_wrapper">Generador de Funciones</span></span></label>
		</div>
		<div class="cs_play_pause">
			<label class="cs_play" for="cs_play1"><span><i></i><b></b></span></label>
			<label class="cs_pause num0" for="cs_pause1_0"><span><i></i><b></b></span></label>
			<label class="cs_pause num1" for="cs_pause1_1"><span><i></i><b></b></span></label>
			<label class="cs_pause num2" for="cs_pause1_2"><span><i></i><b></b></span></label>
			<label class="cs_pause num3" for="cs_pause1_3"><span><i></i><b></b></span></label>
			<label class="cs_pause num4" for="cs_pause1_4"><span><i></i><b></b></span></label>
			</div>
		<div class="cs_arrowprev">
			<label class="num0" for="cs_slide1_0"><span><i></i><b></b></span></label>
			<label class="num1" for="cs_slide1_1"><span><i></i><b></b></span></label>
			<label class="num2" for="cs_slide1_2"><span><i></i><b></b></span></label>
			<label class="num3" for="cs_slide1_3"><span><i></i><b></b></span></label>
			<label class="num4" for="cs_slide1_4"><span><i></i><b></b></span></label>
		</div>
		<div class="cs_arrownext">
			<label class="num0" for="cs_slide1_0"><span><i></i><b></b></span></label>
			<label class="num1" for="cs_slide1_1"><span><i></i><b></b></span></label>
			<label class="num2" for="cs_slide1_2"><span><i></i><b></b></span></label>
			<label class="num3" for="cs_slide1_3"><span><i></i><b></b></span></label>
			<label class="num4" for="cs_slide1_4"><span><i></i><b></b></span></label>
		</div>
		<div class="cs_bullets">
			<label class="num0" for="cs_slide1_0"> <span class="cs_point"></span>
                            <span class="cs_thumb"><img src="Estilos/cssslider_files/csss_tooltips1/brazo.jpg" alt="Brazo Robotico" title="Brazo Robotico"></span></label>
			<label class="num1" for="cs_slide1_1"> <span class="cs_point"></span>
                            <span class="cs_thumb"><img src="Estilos/cssslider_files/csss_tooltips1/rasp.jpg" alt="raspberry pi 2" title="raspberry pi 2"></span></label>
			<label class="num2" for="cs_slide1_2"> <span class="cs_point"></span>
                            <span class="cs_thumb"><img src="Estilos/cssslider_files/csss_tooltips1/daq.jpg" alt="DAQ" title="DAQ"></span></label>
			<label class="num3" for="cs_slide1_3"> <span class="cs_point"></span>
                            <span class="cs_thumb"><img src="Estilos/cssslider_files/csss_tooltips1/fuente.jpg" alt="Fuente" title="Fuente"></span></label>
			<label class="num4" for="cs_slide1_4"> <span class="cs_point"></span>
                            <span class="cs_thumb"><img src="Estilos/cssslider_files/csss_tooltips1/generador_de_funciones.jpg" alt="Generador de Funciones" title="Generador de Funciones"></span></label>
		</div>
		</div>
		<!-- End cssSlider.com -->
            </body>
                
            
          </div> <!-- end div "content" -->
          <div id="footer">
            <ul>
                <li><a href="">Web </a></li>
                <li><a href="">Careers </a></li>
                <li><a href="">Help </a></li>
                <li><a href="">Contact us </a></li>
            </ul>
            &copy; 2016 Materiales de Laboratorio. All Rights Reserved.<br />
            <!-- this is your copyright statement - change the date here -->
          </div> <!-- end div "footer" -->

        </div> <!-- end div "container" -->
    </body>
<!--    <body></body>-->
</html>
